# Generated by Django 4.0.3 on 2022-05-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_tag', models.TextField(blank=True)),
                ('discord_id', models.TextField(blank=True)),
                ('player_class', models.TextField(blank=True)),
                ('player_role', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_name', models.TextField(blank=True)),
                ('difficulty', models.TextField(blank=True)),
                ('level_requirment', models.IntegerField(blank=True)),
                ('faction', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_group', models.TextField(blank=True)),
                ('time', models.TextField(blank=True)),
                ('player_needed', models.IntegerField(blank=True)),
                ('player_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.player')),
                ('raid_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.raid')),
            ],
        ),
    ]
