# Generated by Django 4.0.3 on 2022-05-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
